packages:
  - packages/**

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  ajv@<6.14.0: '^6.14.0'
  axios@>=1.0.0 <1.18.0: '^1.18.0'
  brace-expansion@>=1.0.0 <1.1.18: '^1.1.18'
  brace-expansion@>=2.0.0 <2.1.4: '^2.1.4'
  brace-expansion@>=5.0.0 <5.0.9: '^5.0.9'
  flatted@<3.4.0: '^3.4.0'
  follow-redirects@<1.16.0: '^1.16.0'
  handlebars@<4.7.9: '^4.7.9'
  markdown-it@>=13.0.0 <14.2.0: '^14.2.0'
  minimatch@<3.1.5: '^3.1.5'
  minimatch@>=9.0.0 <9.0.7: '^9.0.7'
  picomatch@<2.3.2: '^2.3.2'
  picomatch@>=4.0.0 <4.0.4: '^4.0.4'
  rollup@>=4.0.0 <4.59.0: '^4.59.0'
  postcss-selector-parser@<7.1.6: '^7.1.6'
  shell-quote@>=1.8.4 <1.11.0: '^1.11.0'
  socket.io-parser@>=4.0.0 <4.2.7: '^4.2.7'
  source-map-js@>=1.0.0 <1.2.2: '^1.2.2'
  ws@>=8.0.0 <8.20.1: '^8.20.1'
  '@istanbuljs/load-nyc-config>js-yaml': '^4.1.1'
